services:
  postgres:
    image: postgres:16-alpine
    container_name: parsers_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: parsers
      POSTGRES_PASSWORD: parsers_secret
      POSTGRES_DB: parsers_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
